version: "3.8"

services:
  kaggle-cpu:
    image: kaggle-cpu
    container_name: kaggle-cpu
    build:
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8888:8888"
    volumes:
      - ../kaggle:/kaggle
    tty: true
